In [16]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [17]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [18]:
df.shape

(569, 33)

In [19]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [20]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

### **train test split**

In [21]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### **Scaling**

In [22]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [23]:
X_train

array([[ 1.06236762e+00,  1.22571454e+00,  9.44056269e-01, ...,
        -1.61047437e-03, -6.59012273e-01, -2.39055932e-01],
       [ 5.61459984e-01, -1.03486352e+00,  5.00808621e-01, ...,
        -1.21601564e-02, -2.11574017e-01, -7.48833162e-01],
       [ 4.52323684e-01, -1.03187841e-02,  6.14670403e-01, ...,
         1.50397986e+00,  2.18401694e+00,  1.15084951e+00],
       ...,
       [-1.22893501e+00, -3.38175165e-02, -1.22216412e+00, ...,
        -1.02206614e+00,  4.71014273e-01, -2.05833270e-01],
       [-3.48009185e-01, -1.44374146e+00, -4.10492277e-01, ...,
        -9.04964673e-01, -9.77444609e-01, -8.01662640e-01],
       [ 1.78434622e+00,  2.00822234e+00,  1.72482277e+00, ...,
         6.41920127e-01, -7.68422358e-01, -3.20950899e-02]])

In [24]:
y_train

274    M
406    B
351    M
177    M
229    M
      ..
48     B
488    B
424    B
287    B
233    M
Name: diagnosis, Length: 455, dtype: object

### **Lable Encoding**

In [25]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [26]:
y_train

array([1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1])

##3 **Numpy Arrays to PyTorch Tensors**

In [28]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [29]:
X_train_tensor.shape

torch.Size([455, 30])

In [30]:
y_train_tensor.shape

torch.Size([455])

In [31]:
from torch.utils.data import Dataset, DataLoader

In [32]:
class CustomDataset(Dataset):
  def __init__(self, features, lables):
    self.features = features
    self.lables = lables

  def __len__(self):
    return len(self.features)

  def __getitem__(self, idx):
    return self.features[idx], self.lables[idx]

In [33]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [35]:
train_dataset[1]

(tensor([ 0.5615, -1.0349,  0.5008,  0.3989, -0.0886, -0.3521, -0.4155, -0.0887,
         -0.2967, -0.5522, -0.6031, -1.0284, -0.5614, -0.4023, -1.0872, -0.7065,
         -0.4280, -0.4745, -0.6855, -0.8024,  0.2919, -0.9965,  0.2540,  0.1112,
         -0.5233, -0.5049, -0.1893, -0.0122, -0.2116, -0.7488]),
 tensor(0.))

In [36]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

### **Defining Model**

In [37]:
import torch.nn as nn                                                                     # Using NN Module

class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

### **Important Parameters**

In [38]:
learning_rate = 0.1
epochs = 25

In [39]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# Define Optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# Define Loss Function
loss_function = nn.BCELoss()

### **Training Pipeline**

In [40]:
# define loop
for epoch in range(epochs):

  for batch_features, batch_lables in train_loader:

    # forward pass
    y_pred = model(X_train_tensor)

    # loss calculate
    loss = loss_function(y_pred, y_train_tensor.view(-1, 1))

    # zero gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.9913339614868164
Epoch: 1, Loss: 0.6761871576309204
Epoch: 1, Loss: 0.5165250301361084
Epoch: 1, Loss: 0.43126803636550903
Epoch: 1, Loss: 0.37805917859077454
Epoch: 1, Loss: 0.3412245512008667
Epoch: 1, Loss: 0.3139331042766571
Epoch: 1, Loss: 0.29272255301475525
Epoch: 1, Loss: 0.2756442129611969
Epoch: 1, Loss: 0.26151415705680847
Epoch: 1, Loss: 0.24957025051116943
Epoch: 1, Loss: 0.2392987161874771
Epoch: 1, Loss: 0.23033969104290009
Epoch: 1, Loss: 0.22243335843086243
Epoch: 1, Loss: 0.21538686752319336
Epoch: 2, Loss: 0.2090538740158081
Epoch: 2, Loss: 0.20332103967666626
Epoch: 2, Loss: 0.19809909164905548
Epoch: 2, Loss: 0.1933164894580841
Epoch: 2, Loss: 0.18891529738903046
Epoch: 2, Loss: 0.18484781682491302
Epoch: 2, Loss: 0.18107450008392334
Epoch: 2, Loss: 0.17756211757659912
Epoch: 2, Loss: 0.174282506108284
Epoch: 2, Loss: 0.1712116301059723
Epoch: 2, Loss: 0.1683288961648941
Epoch: 2, Loss: 0.16561633348464966
Epoch: 2, Loss: 0.16305837035179138
Epoch: 2, Loss: 0.16064131259918213
Epoch: 2, Loss: 0.15835316479206085
Epoch: 3, Loss: 0.15618321299552917
Epoch: 3, Loss: 0.1541220247745514
Epoch: 3, Loss: 0.15216109156608582
Epoch: 3, Loss: 0.15029287338256836
Epoch: 3, Loss: 0.14851054549217224
Epoch: 3, Loss: 0.1468079686164856
Epoch: 3, Loss: 0.14517956972122192
Epoch: 3, Loss: 0.14362028241157532
Epoch: 3, Loss: 0.14212562143802643
Epoch: 3, Loss: 0.140691339969635
Epoch: 3, Loss: 0.13931363821029663
Epoch: 3, Loss: 0.13798899948596954
Epoch: 3, Loss: 0.13671424984931946
Epoch: 3, Loss: 0.13548643887043
Epoch: 3, Loss: 0.13430282473564148
Epoch: 4, Loss: 0.13316093385219574
Epoch: 4, Loss: 0.13205844163894653
Epoch: 4, Loss: 0.13099321722984314
Epoch: 4, Loss: 0.1299632340669632
Epoch: 4, Loss: 0.12896667420864105
Epoch: 4, Loss: 0.1280018538236618
Epoch: 4, Loss: 0.12706714868545532
Epoch: 4, Loss: 0.12616105377674103
Epoch: 4, Loss: 0.1252821832895279
Epoch: 4, Loss: 0.12442927062511444
Epoch: 4, Loss: 0.12360106408596039
Epoch: 4, Loss: 0.1227964460849762
Epoch: 4, Loss: 0.1220143511891365
Epoch: 4, Loss: 0.12125375866889954
Epoch: 4, Loss: 0.12051372975111008
Epoch: 5, Loss: 0.11979339271783829
Epoch: 5, Loss: 0.11909189075231552
Epoch: 5, Loss: 0.1184084564447403
Epoch: 5, Loss: 0.11774234473705292
Epoch: 5, Loss: 0.11709281802177429
Epoch: 5, Loss: 0.11645927280187607
Epoch: 5, Loss: 0.11584104597568512
Epoch: 5, Loss: 0.11523754149675369
Epoch: 5, Loss: 0.11464820802211761
Epoch: 5, Loss: 0.11407250910997391
Epoch: 5, Loss: 0.11350993812084198
Epoch: 5, Loss: 0.11296001821756363
Epoch: 5, Loss: 0.11242228746414185
Epoch: 5, Loss: 0.11189629882574081
Epoch: 5, Loss: 0.11138167232275009
Epoch: 6, Loss: 0.11087797582149506
Epoch: 6, Loss: 0.11038486659526825
Epoch: 6, Loss: 0.10990197211503983
Epoch: 6, Loss: 0.10942893475294113
Epoch: 6, Loss: 0.1089654490351677
Epoch: 6, Loss: 0.10851121693849564
Epoch: 6, Loss: 0.10806591808795929
Epoch: 6, Loss: 0.10762927681207657
Epoch: 6, Loss: 0.10720101743936539
Epoch: 6, Loss: 0.10678088665008545
Epoch: 6, Loss: 0.10636860877275467
Epoch: 6, Loss: 0.10596399754285812
Epoch: 6, Loss: 0.10556676983833313
Epoch: 6, Loss: 0.10517673939466476
Epoch: 6, Loss: 0.10479369014501572
Epoch: 7, Loss: 0.10441740602254868
Epoch: 7, Loss: 0.10404770076274872
Epoch: 7, Loss: 0.10368439555168152
Epoch: 7, Loss: 0.10332730412483215
Epoch: 7, Loss: 0.1029762327671051
Epoch: 7, Loss: 0.10263106226921082
Epoch: 7, Loss: 0.10229161381721497
Epoch: 7, Loss: 0.10195770114660263
Epoch: 7, Loss: 0.10162920504808426
Epoch: 7, Loss: 0.1013059914112091
Epoch: 7, Loss: 0.10098789632320404
Epoch: 7, Loss: 0.1006748303771019
Epoch: 7, Loss: 0.10036661475896835
Epoch: 7, Loss: 0.10006314516067505
Epoch: 7, Loss: 0.09976430982351303
Epoch: 8, Loss: 0.09946998208761215
Epoch: 8, Loss: 0.09918006509542465
Epoch: 8, Loss: 0.09889443963766098
Epoch: 8, Loss: 0.09861301630735397
Epoch: 8, Loss: 0.09833566844463348
Epoch: 8, Loss: 0.09806232899427414
Epoch: 8, Loss: 0.09779287129640579
Epoch: 8, Loss: 0.09752724319696426
Epoch: 8, Loss: 0.09726532548666
Epoch: 8, Loss: 0.09700704365968704
Epoch: 8, Loss: 0.09675231575965881
Epoch: 8, Loss: 0.09650105983018875
Epoch: 8, Loss: 0.09625319391489029
Epoch: 8, Loss: 0.09600865095853806
Epoch: 8, Loss: 0.09576736390590668
Epoch: 9, Loss: 0.09552925825119019
Epoch: 9, Loss: 0.09529423713684082
Epoch: 9, Loss: 0.09506229311227798
Epoch: 9, Loss: 0.09483329951763153
Epoch: 9, Loss: 0.09460723400115967
Epoch: 9, Loss: 0.09438401460647583
Epoch: 9, Loss: 0.09416358172893524
Epoch: 9, Loss: 0.09394589811563492
Epoch: 9, Loss: 0.09373090416193008
Epoch: 9, Loss: 0.09351852536201477
Epoch: 9, Loss: 0.0933087170124054
Epoch: 9, Loss: 0.09310143440961838
Epoch: 9, Loss: 0.09289663285017014
Epoch: 9, Loss: 0.0926942527294159
Epoch: 9, Loss: 0.09249424189329147
Epoch: 10, Loss: 0.09229656308889389
Epoch: 10, Loss: 0.09210117906332016
Epoch: 10, Loss: 0.0919080302119255
Epoch: 10, Loss: 0.09171708673238754
Epoch: 10, Loss: 0.09152831882238388
Epoch: 10, Loss: 0.09134164452552795
Epoch: 10, Loss: 0.09115705639123917
Epoch: 10, Loss: 0.09097451716661453
Epoch: 10, Loss: 0.09079398214817047
Epoch: 10, Loss: 0.0906153991818428
Epoch: 10, Loss: 0.09043876826763153
Epoch: 10, Loss: 0.09026402980089188
Epoch: 10, Loss: 0.09009115397930145
Epoch: 10, Loss: 0.08992011845111847
Epoch: 10, Loss: 0.08975086361169815
Epoch: 11, Loss: 0.0895833894610405
Epoch: 11, Loss: 0.08941765129566193
Epoch: 11, Loss: 0.08925361931324005
Epoch: 11, Loss: 0.08909126371145248
Epoch: 11, Loss: 0.08893057703971863
Epoch: 11, Loss: 0.08877149224281311
Epoch: 11, Loss: 0.08861401677131653
Epoch: 11, Loss: 0.0884580984711647
Epoch: 11, Loss: 0.08830372989177704
Epoch: 11, Loss: 0.08815088123083115
Epoch: 11, Loss: 0.08799952268600464
Epoch: 11, Loss: 0.08784963935613632
Epoch: 11, Loss: 0.08770118653774261
Epoch: 11, Loss: 0.08755417168140411
Epoch: 11, Loss: 0.08740855008363724
Epoch: 12, Loss: 0.08726430684328079
Epoch: 12, Loss: 0.08712143450975418
Epoch: 12, Loss: 0.08697985857725143
Epoch: 12, Loss: 0.08683962374925613
Epoch: 12, Loss: 0.0867006778717041
Epoch: 12, Loss: 0.08656300604343414
Epoch: 12, Loss: 0.08642658591270447
Epoch: 12, Loss: 0.08629141747951508
Epoch: 12, Loss: 0.08615745604038239
Epoch: 12, Loss: 0.0860246792435646
Epoch: 12, Loss: 0.08589310199022293
Epoch: 12, Loss: 0.08576268702745438
Epoch: 12, Loss: 0.08563340455293655
Epoch: 12, Loss: 0.08550526201725006
Epoch: 12, Loss: 0.0853782370686531
Epoch: 13, Loss: 0.0852523073554039
Epoch: 13, Loss: 0.08512745052576065
Epoch: 13, Loss: 0.08500365912914276
Epoch: 13, Loss: 0.08488094061613083
Epoch: 13, Loss: 0.08475923538208008
Epoch: 13, Loss: 0.0846385583281517
Epoch: 13, Loss: 0.08451888710260391
Epoch: 13, Loss: 0.0844002217054367
Epoch: 13, Loss: 0.0842825174331665
Epoch: 13, Loss: 0.0841657817363739
Epoch: 13, Loss: 0.0840500071644783
Epoch: 13, Loss: 0.08393517881631851
Epoch: 13, Loss: 0.08382125943899155
Epoch: 13, Loss: 0.083708256483078
Epoch: 13, Loss: 0.08359616249799728
Epoch: 14, Loss: 0.0834849625825882
Epoch: 14, Loss: 0.08337462693452835
Epoch: 14, Loss: 0.08326517790555954
Epoch: 14, Loss: 0.08315657824277878
Epoch: 14, Loss: 0.08304881304502487
Epoch: 14, Loss: 0.08294188231229782
Epoch: 14, Loss: 0.08283577859401703
Epoch: 14, Loss: 0.0827304944396019
Epoch: 14, Loss: 0.08262600749731064
Epoch: 14, Loss: 0.08252230286598206
Epoch: 14, Loss: 0.08241939544677734
Epoch: 14, Loss: 0.08231724053621292
Epoch: 14, Loss: 0.08221586793661118
Epoch: 14, Loss: 0.08211524039506912
Epoch: 14, Loss: 0.08201534301042557
Epoch: 15, Loss: 0.0819161906838417
Epoch: 15, Loss: 0.08181775361299515
Epoch: 15, Loss: 0.08172004669904709
Epoch: 15, Loss: 0.08162304013967514
Epoch: 15, Loss: 0.0815267339348793
Epoch: 15, Loss: 0.08143112063407898
Epoch: 15, Loss: 0.08133617788553238
Epoch: 15, Loss: 0.0812419205904007
Epoch: 15, Loss: 0.08114832639694214
Epoch: 15, Loss: 0.08105539530515671
Epoch: 15, Loss: 0.08096309751272202
Epoch: 15, Loss: 0.08087146282196045
Epoch: 15, Loss: 0.08078044652938843
Epoch: 15, Loss: 0.08069006353616714
Epoch: 15, Loss: 0.0806003138422966
Epoch: 16, Loss: 0.08051115274429321
Epoch: 16, Loss: 0.08042262494564056
Epoch: 16, Loss: 0.08033467084169388
Epoch: 16, Loss: 0.08024732023477554
Epoch: 16, Loss: 0.08016056567430496
Epoch: 16, Loss: 0.08007437735795975
Epoch: 16, Loss: 0.0799887627363205
Epoch: 16, Loss: 0.07990372180938721
Epoch: 16, Loss: 0.07981923967599869
Epoch: 16, Loss: 0.07973529398441315
Epoch: 16, Loss: 0.07965190708637238
Epoch: 16, Loss: 0.07956907153129578
Epoch: 16, Loss: 0.07948677241802216
Epoch: 16, Loss: 0.07940499484539032
Epoch: 16, Loss: 0.07932373881340027
Epoch: 17, Loss: 0.0792429968714714
Epoch: 17, Loss: 0.07916278392076492
Epoch: 17, Loss: 0.07908306270837784
Epoch: 17, Loss: 0.07900384813547134
Epoch: 17, Loss: 0.07892514020204544
Epoch: 17, Loss: 0.07884691655635834
Epoch: 17, Loss: 0.07876916974782944
Epoch: 17, Loss: 0.07869192212820053
Epoch: 17, Loss: 0.07861514389514923
Epoch: 17, Loss: 0.07853883504867554
Epoch: 17, Loss: 0.07846298813819885
Epoch: 17, Loss: 0.07838761061429977
Epoch: 17, Loss: 0.0783126950263977
Epoch: 17, Loss: 0.07823822647333145
Epoch: 17, Loss: 0.07816419750452042
Epoch: 18, Loss: 0.0780906081199646
Epoch: 18, Loss: 0.0780174657702446
Epoch: 18, Loss: 0.07794476300477982
Epoch: 18, Loss: 0.07787247747182846
Epoch: 18, Loss: 0.07780063152313232
Epoch: 18, Loss: 0.07772919535636902
Epoch: 18, Loss: 0.07765818387269974
Epoch: 18, Loss: 0.07758758217096329
Epoch: 18, Loss: 0.07751739025115967
Epoch: 18, Loss: 0.07744760811328888
Epoch: 18, Loss: 0.07737821340560913
Epoch: 18, Loss: 0.07730922847986221
Epoch: 18, Loss: 0.07724063098430634
Epoch: 18, Loss: 0.0771724209189415
Epoch: 18, Loss: 0.0771045982837677
Epoch: 19, Loss: 0.07703715562820435
Epoch: 19, Loss: 0.07697010040283203
Epoch: 19, Loss: 0.07690341770648956
Epoch: 19, Loss: 0.07683710753917694
Epoch: 19, Loss: 0.07677116245031357
Epoch: 19, Loss: 0.07670558243989944
Epoch: 19, Loss: 0.07664035260677338
Epoch: 19, Loss: 0.07657549530267715
Epoch: 19, Loss: 0.07651098817586899
Epoch: 19, Loss: 0.07644682377576828
Epoch: 19, Loss: 0.07638301700353622
Epoch: 19, Loss: 0.07631955295801163
Epoch: 19, Loss: 0.07625642418861389
Epoch: 19, Loss: 0.07619363814592361
Epoch: 19, Loss: 0.0761311873793602
Epoch: 20, Loss: 0.07606907188892365
Epoch: 20, Loss: 0.07600728422403336
Epoch: 20, Loss: 0.07594581693410873
Epoch: 20, Loss: 0.07588467746973038
Epoch: 20, Loss: 0.07582385838031769
Epoch: 20, Loss: 0.07576335221529007
Epoch: 20, Loss: 0.07570317387580872
Epoch: 20, Loss: 0.07564329355955124
Epoch: 20, Loss: 0.07558372616767883
Epoch: 20, Loss: 0.0755244717001915
Epoch: 20, Loss: 0.07546550780534744
Epoch: 20, Loss: 0.07540685683488846
Epoch: 20, Loss: 0.07534850388765335
Epoch: 20, Loss: 0.07529044151306152
Epoch: 20, Loss: 0.07523267716169357
Epoch: 21, Loss: 0.0751752108335495
Epoch: 21, Loss: 0.07511801272630692
Epoch: 21, Loss: 0.07506111264228821
Epoch: 21, Loss: 0.07500449568033218
Epoch: 21, Loss: 0.07494816184043884
Epoch: 21, Loss: 0.07489210367202759
Epoch: 21, Loss: 0.07483632117509842
Epoch: 21, Loss: 0.07478082925081253
Epoch: 21, Loss: 0.07472558319568634
Epoch: 21, Loss: 0.07467061281204224
Epoch: 21, Loss: 0.07461592555046082
Epoch: 21, Loss: 0.07456148415803909
Epoch: 21, Loss: 0.07450731843709946
Epoch: 21, Loss: 0.07445341348648071
Epoch: 21, Loss: 0.07439976185560226
Epoch: 22, Loss: 0.07434637099504471
Epoch: 22, Loss: 0.07429323345422745
Epoch: 22, Loss: 0.07424034923315048
Epoch: 22, Loss: 0.07418770343065262
Epoch: 22, Loss: 0.07413531839847565
Epoch: 22, Loss: 0.07408317923545837
Epoch: 22, Loss: 0.0740312784910202
Epoch: 22, Loss: 0.07397963106632233
Epoch: 22, Loss: 0.07392821460962296
Epoch: 22, Loss: 0.07387703657150269
Epoch: 22, Loss: 0.07382609695196152
Epoch: 22, Loss: 0.07377539575099945
Epoch: 22, Loss: 0.07372492551803589
Epoch: 22, Loss: 0.07367467880249023
Epoch: 22, Loss: 0.07362467050552368
Epoch: 23, Loss: 0.07357489317655563
Epoch: 23, Loss: 0.0735253319144249
Epoch: 23, Loss: 0.07347600162029266
Epoch: 23, Loss: 0.07342688739299774
Epoch: 23, Loss: 0.07337799668312073
Epoch: 23, Loss: 0.07332932949066162
Epoch: 23, Loss: 0.07328087836503983
Epoch: 23, Loss: 0.07323263585567474
Epoch: 23, Loss: 0.07318461686372757
Epoch: 23, Loss: 0.07313679903745651
Epoch: 23, Loss: 0.07308921217918396
Epoch: 23, Loss: 0.07304181903600693
Epoch: 23, Loss: 0.07299462705850601
Epoch: 23, Loss: 0.072947658598423
Epoch: 23, Loss: 0.07290088385343552
Epoch: 24, Loss: 0.07285430282354355
Epoch: 24, Loss: 0.07280793786048889
Epoch: 24, Loss: 0.07276177406311035
Epoch: 24, Loss: 0.07271580398082733
Epoch: 24, Loss: 0.07267002761363983
Epoch: 24, Loss: 0.07262445986270905
Epoch: 24, Loss: 0.07257907837629318
Epoch: 24, Loss: 0.07253388315439224
Epoch: 24, Loss: 0.07248888164758682
Epoch: 24, Loss: 0.07244407385587692
Epoch: 24, Loss: 0.07239945232868195
Epoch: 24, Loss: 0.07235501706600189
Epoch: 24, Loss: 0.07231078296899796
Epoch: 24, Loss: 0.07226671278476715
Epoch: 24, Loss: 0.07222283631563187
Epoch: 25, Loss: 0.07217913866043091
Epoch: 25, Loss: 0.07213560491800308
Epoch: 25, Loss: 0.07209227979183197
Epoch: 25, Loss: 0.07204912602901459
Epoch: 25, Loss: 0.07200614362955093
Epoch: 25, Loss: 0.0719633400440216
Epoch: 25, Loss: 0.07192070782184601
Epoch: 25, Loss: 0.07187824696302414
Epoch: 25, Loss: 0.0718359649181366
Epoch: 25, Loss: 0.07179385423660278
Epoch: 25, Loss: 0.0717519074678421
Epoch: 25, Loss: 0.07171013206243515
Epoch: 25, Loss: 0.07166851311922073
Epoch: 25, Loss: 0.07162707298994064
Epoch: 25, Loss: 0.07158579677343369

### **Evaluation**

In [41]:
# model evaluation using test_loader
model.eval()                              #Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_lables in test_loader:
    #Forward Pass
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.9).float()                     #Convert probabilities to binary predictions
    #Calculate accuracy for the current batch
    batch_accuracy = (y_pred.view(-1) == batch_lables).float().mean()
    accuracy_list.append(batch_accuracy)

#Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')

Accuracy: 0.9453