In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [ ]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

### **train test split**

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### **Scaling**

In [ ]:
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.fit_transform(X_test)

In [ ]:
X_train

array([[-0.07666971,  0.73609083, -0.02772755, ...,  0.83563556,
         0.31632713,  0.55738443],
       [ 3.40426403, -0.42004014,  3.50291987, ...,  2.49784626,
         1.29500926,  0.26819659],
       [-1.21001051, -0.46551941, -1.19841368, ..., -0.87446153,
         0.17032701, -0.53293187],
       ...,
       [ 1.56193037,  1.02572198,  1.59754476, ...,  0.66834012,
         0.05962362, -0.40229489],
       [-0.75772197, -0.45594483, -0.74467246, ..., -0.74952714,
        -0.47945375, -0.13320505],
       [-0.3648072 , -0.65222379, -0.41894204, ..., -0.82933781,
        -0.80193753, -1.07446121]])

In [ ]:
y_train

196    M
352    M
206    B
82     M
309    B
      ..
496    B
411    B
244    M
142    B
69     B
Name: diagnosis, Length: 455, dtype: object

### **Lable Encoding**

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [ ]:
y_train

array([1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0])

### **Numpy arrays to Tensors**

In [ ]:
X_train_tensors = torch.from_numpy(X_train)
X_test_tensors = torch.from_numpy(X_test)
y_train_tensors = torch.from_numpy(y_train)
y_test_tensors = torch.from_numpy(y_test)

In [ ]:
X_train_tensors.shape

torch.Size([455, 30])

In [ ]:
y_train_tensors.shape

torch.Size([455])

### **Defining The Modal**

In [ ]:
class MySimpleNN():
  def __init__(self, X):
    self.weights = torch.rand(X.shape[1],1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred


  def loss_function(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)


    # Calculate loss
    loss = -(y_train_tensors * torch.log(y_pred) + (1 - y_train_tensors) * torch.log(1-y_pred)).mean()
    return loss

#### **Important Parameters**

In [ ]:
learning_rate = 0.1
epochs = 25

### **Training Pipeline**

In [ ]:
# Create modal
model = MySimpleNN(X_train_tensors)

# Define loop
for epoch in range(epochs):

  # Forward Pass
  y_pred = model.forward(X_train_tensors)

  # Loss Calculate
  loss = model.loss_function(y_pred, y_train_tensors)

  # Backward Pass
  loss.backward()

  # Update Parameters
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # Zero Gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # Print Loss in each epoch
  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.1820889742453136
Epoch: 2, Loss: 3.055792240231055
Epoch: 3, Loss: 2.928099120178463
Epoch: 4, Loss: 2.800402508833997
Epoch: 5, Loss: 2.6713121963792403
Epoch: 6, Loss: 2.53556046236996
Epoch: 7, Loss: 2.395280180394157
Epoch: 8, Loss: 2.2559888294135884
Epoch: 9, Loss: 2.1203565307827477
Epoch: 10, Loss: 1.9835854836826115
Epoch: 11, Loss: 1.8457085490832577
Epoch: 12, Loss: 1.7161468566315135
Epoch: 13, Loss: 1.595750064593827
Epoch: 14, Loss: 1.4852973321354732
Epoch: 15, Loss: 1.3825860997836252
Epoch: 16, Loss: 1.283564595642731
Epoch: 17, Loss: 1.196991547630983
Epoch: 18, Loss: 1.1227512111359437
Epoch: 19, Loss: 1.0602159812926435
Epoch: 20, Loss: 1.0082650969658808
Epoch: 21, Loss: 0.9653988906650403
Epoch: 22, Loss: 0.9299613785155376
Epoch: 23, Loss: 0.9003925630749836
Epoch: 24, Loss: 0.8753889185196382
Epoch: 25, Loss: 0.8539421588294285

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensors)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensors).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5846414566040039